services:
  # Catalog database configuration
  catalogdb:
    image: mongo
  
  # Catalog api configuration
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      
volumes:
  mongo_data: