services:
  # Catalog database configuration
  catalogdb:
    image: mongo
  
  # Basket database configuration
  basketdb:
    image: redis:alpine
    
  # Discount database configuration
  discountdb:
    image: postgres
    
  # Ordering database configuration
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    
  # RabbitMQ configuration
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  # Catalog api configuration
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  # Basket api configuration
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
      
  # Discount api configuration
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
  
  # Ordering api configuration
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
  
  # Portainer configuration
  portainer:
    image: portainer/portainer-ce
    
  # PgAdmin configuration
  pgadmin:
    image: dpage/pgadmin4
      
volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: